INSERT INTO  SEGURANCA (SEG_SENHA, SEG_SALT, SEG_ANTIPHISHING, SEG_TELEFONE)
VALUES  ('AASFASFASDWQW', 'ASDASFGASF', 'ASDASDASD', '12512312');

INSERT INTO USERS (USR_ID, USR_NOME, USR_CPF, USR_EMAIL, USR_SALDO, SEG_SENHA)
VALUES ('1', 'John Doe', '12412512', 'john@doe', '2.62', 'AASFASFASDWQW');