[global]
username = "davidlevycostabri_7@hotmail.com"
password = "DDD@LLL777"
device_name = "ArchDesktop"
device_type = "computer"
backend = "pulseaudio"
bitrate = 320
cache_path = "/home/davidlevy/.cache/spotifyd"
max_cache_size = 5000000000
initial_volume = "60"
autoplay = true
zeroconf_port = 4444
